### ISSUE TITLE
Rename "Merchant ID" to "Initiating Party ID"?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/pronamic-pay-worldline-open-banking-ideal-2#1]
Should we rename "Merchant ID" to "Initiating Party ID"?

https://github.com/pronamic/pronamic-pay-worldline-open-banking-ideal-2/blob/2acb3e50bcdffebf340b2c1fa78bc91395008f20/src/Integration.php#L102-L121

> | Header | Value | Description |
> | --- | --- | --- |
> | App | `IDEAL` | App value is always IDEAL for iDEAL transactions. |
> | Client | `RaboiDEAL` | Client value is always RaboiDEAL for Merchants with Rabobank |
> | Id | _Initiating Party ID*_ | This is the identifier used by the Open Banking Service to identify the Merchant.<br>In the test environment, only the test Merchants should be used. |
>
> `*` The Initiating Party ID for a Merchant can be found in the Rabo iDEAL Dashboard via the Merchant Page or
the Subscription Page. This is also known as **"Dashboard ID"** for Rabobank Merchants. Please note this is to
be taken from the Rabo iDEAL Dashboard l for transactions in **Production**.

_Source: `iDEAL_2.0_Getting_Started_Guide_-_version_1.4 - Rabobank.pdf`_

CC @rvdsteege

**Comment by remcotolsma** [comment]
From `iDEAL_2.0_Getting_Started_Guide_-_version_1.4 - ABN AMRO.pdf`:

> `*` *The Initiating Party ID for a Merchant can be found in the iDEAL Merchant Portal via the Merchant Page or the Subscription Page. This is also known as **"BC number"** for ABN Amro Merchants. Please note this is to be taken from the iDEAL merchant Portal for transactions in **Production**.

**Comment by rvdsteege** [comment]
Fixed in https://github.com/pronamic/pronamic-pay-worldline-open-banking-ideal-2/compare/2acb3e5…a5a047a.
