### ISSUE TITLE
Store iDEAL transaction ID in payment

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/pronamic-pay-worldline-open-banking-ideal-2#5]
We're using a `PaymentID` from the response on payment initiation as the transaction ID of the payment:

https://github.com/pronamic/pronamic-pay-worldline-open-banking-ideal-2/blob/cd3c331eb1cb64e5354ef8c7d95bec8856b4cca1/src/Gateway.php#L83-L85

This ID (e.g. `190XXX`) refers to the payment in the Open Banking Service and needs to be used in subsequent API calls, but is not mentioned in bank statements.

At support, a customer wants to use the bank statement transaction ID (e.g. `7020067062XXXXXX`) for matching in Salesforce. Therefore it would be beneficial to also have this ID available within the Pronamic payment. I'm guessing that this ID can be obtained through `AspspPaymentId` in the `201 Created` response on payment initiation:

> - `PaymentId` (required): Id generated by the Open Banking Service. This should be used to refer to this payment in subsequent api calls.
> - `AspspPaymentId`: Id used by the ASPSP/iDEAL Hub to refer to the payment.
> 
> _Source: https://financial-services.developer.worldline.com/node/274#operation/paymentInitiate_

Maybe we can store the ID in payment meta, @remcotolsma? Thoughts?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2506036239/26882_

**Comment by remcotolsma** [comment]
Yes, saving in payment meta seems fine to me. With the following meta keys?

- `worldline_open_banking_payment_id`
- `worldline_open_banking_aspsp_payment_id`

Is it also better to store `AspspPaymentId` as transaction ID?

**Comment by dorcasit** [comment]
@remcotolsma, for us it's important that the transactionID remains the same as before in this format: 7020067062XXXXXX
And is identical to the transactionID that is on the transaction itself when you open your banking app.
